# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: device.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'device.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x64\x65vice.proto\x12\x0fnetvisor.device\x1a\x0c\x63ommon.proto\"\xe7\x01\n\x10\x44iscoveredDevice\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0b\n\x03mac\x18\x02 \x01(\t\x12\x10\n\x08hostname\x18\x03 \x01(\t\x12\x0e\n\x06vendor\x18\x04 \x01(\t\x12\x13\n\x0b\x64\x65vice_type\x18\x05 \x01(\t\x12\x11\n\tos_family\x18\x06 \x01(\t\x12\x11\n\tis_online\x18\x07 \x01(\x08\x12.\n\nfirst_seen\x18\x08 \x01(\x0b\x32\x1a.netvisor.common.Timestamp\x12-\n\tlast_seen\x18\t \x01(\x0b\x32\x1a.netvisor.common.Timestamp\"\xa7\x01\n\x0b\x44\x65viceBatch\x12/\n\x06sender\x18\x01 \x01(\x0b\x32\x1f.netvisor.common.ClientIdentity\x12\x32\n\x07\x64\x65vices\x18\x02 \x03(\x0b\x32!.netvisor.device.DiscoveredDevice\x12\x33\n\x0f\x62\x61tch_timestamp\x18\x03 \x01(\x0b\x32\x1a.netvisor.common.Timestampb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'device_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DISCOVEREDDEVICE']._serialized_start=48
  _globals['_DISCOVEREDDEVICE']._serialized_end=279
  _globals['_DEVICEBATCH']._serialized_start=282
  _globals['_DEVICEBATCH']._serialized_end=449
# @@protoc_insertion_point(module_scope)
