OUI_VENDOR_PREFIXES = {
    "00:50:56": "VMware",
    "00:0C:29": "VMware",
    "00:05:69": "VMware",
    "00:1C:14": "VMware",
    "08:00:27": "Oracle VirtualBox",
    "00:15:5D": "Microsoft Hyper-V",
    "DC:A6:32": "Raspberry Pi",
    "B8:27:EB": "Raspberry Pi",
    "D8:3A:DD": "Ubiquiti",
    "F0:9F:C2": "Ubiquiti",
    "00:11:32": "Synology",
    "06:C9:80": "OPPO / Android",
    "24:A1:60": "OPPO / Android",
    "48:74:6E": "OPPO / Android",
    "80:35:C1": "OPPO / Android",
    "A4:83:E7": "OPPO / Android",
    "B0:19:21": "OPPO / Android",
    "F4:1A:9C": "OPPO / Android",
    "28:6A:BA": "Apple",
    "3C:22:FB": "Apple",
    "7C:D1:C3": "Apple",
    "A4:C3:F0": "Apple",
    "F0:18:98": "Apple",
    "18:65:90": "Samsung",
    "34:23:BA": "Samsung",
    "5C:F6:DC": "Samsung",
    "A0:21:B7": "Samsung",
    "D0:17:C2": "Samsung",
    "64:CC:2E": "Xiaomi",
    "78:02:F8": "Xiaomi",
    "A4:50:46": "Xiaomi",
    "C8:3A:35": "Xiaomi",
    "F8:A4:5F": "Xiaomi",
}

MOBILE_VENDOR_MARKERS = {"android", "oppo", "samsung", "xiaomi", "redmi", "oneplus", "vivo", "realme", "apple"}

HOSTNAME_TYPE_HINTS = {
    "iphone": "Mobile Phone",
    "ipad": "Tablet",
    "android": "Mobile Phone",
    "oppo": "Mobile Phone",
    "reno": "Mobile Phone",
    "samsung": "Mobile Phone",
    "galaxy": "Mobile Phone",
    "redmi": "Mobile Phone",
    "xiaomi": "Mobile Phone",
    "oneplus": "Mobile Phone",
    "vivo": "Mobile Phone",
    "realme": "Mobile Phone",
    "printer": "Printer",
    "chromecast": "Chromecast / Smart TV",
    "roku": "Roku / Smart TV",
    "tv": "Smart TV",
    "desktop": "Windows Device",
    "laptop": "Laptop",
    "raspberry": "Linux/IoT Device",
    "synology": "NAS / Storage",
}
