const baseScene = {
  eyebrow: 'Operational Workspace',
  headline: 'Command every signal from one live console',
  description: 'A readable security workspace with cinematic depth, live telemetry, and investigation-ready posture.',
  mood: 'Calm command core',
  quote: 'Clarity is the first control.',
  signature: 'NetVisor Core',
  strip: ['Telemetry', 'Posture', 'Evidence'],
};

export const THEMES = {
  core: {
    id: 'core',
    label: 'NetVisor Core',
    description: 'Balanced dark SOC workspace for daily operations.',
    category: 'standard',
    icon: 'ri-radar-line',
    font: "'Inter', sans-serif",
    displayFont: "'Inter', sans-serif",
    preview: {
      primary: '#54c8e8',
      secondary: '#2dd4bf',
      surface: '#07111c',
      gradient: 'linear-gradient(135deg, #07111c 0%, #12344a 52%, #54c8e8 100%)',
    },
    scene: baseScene,
    gpuCost: 'low',
    effects: {
      particles: true,
      scanlines: false,
      sakura: false,
      grid: false,
      glowIntensity: 0.15,
      terminalTyping: false,
    },
  },
  'cyberpunk-tokyo': {
    id: 'cyberpunk-tokyo',
    label: 'Cyberpunk Tokyo',
    description: 'Neon city operations with magenta/cyan grid energy.',
    category: 'flagship',
    icon: 'ri-flashlight-line',
    font: "'Rajdhani', 'Inter', sans-serif",
    displayFont: "'Orbitron', 'Rajdhani', sans-serif",
    preview: {
      primary: '#ff007f',
      secondary: '#00f0ff',
      surface: '#090212',
      gradient: 'linear-gradient(135deg, #090212 0%, #34115d 42%, #ff007f 70%, #00f0ff 100%)',
    },
    scene: {
      eyebrow: 'Neon District Watch',
      headline: 'Route incidents through a live city of signals',
      description: 'High-contrast city-grid intelligence for traffic spikes, suspicious conversations, and rapid analyst triage.',
      mood: 'Rainlit neon command deck',
      quote: 'The city speaks in packets.',
      signature: 'Neon Grid',
      strip: ['Neon Grid', 'Signal Rain', 'Street-Level Telemetry'],
    },
    gpuCost: 'medium',
    effects: {
      particles: true,
      scanlines: false,
      sakura: false,
      grid: true,
      glowIntensity: 0.8,
      terminalTyping: false,
    },
  },
  'matrix-terminal': {
    id: 'matrix-terminal',
    label: 'Matrix Terminal',
    description: 'Green phosphor command line for logs, flows, and raw signal clarity.',
    category: 'flagship',
    icon: 'ri-terminal-box-line',
    font: "'JetBrains Mono', monospace",
    displayFont: "'IBM Plex Mono', 'JetBrains Mono', monospace",
    preview: {
      primary: '#00ff41',
      secondary: '#008f11',
      surface: '#000a00',
      gradient: 'linear-gradient(135deg, #000000 0%, #002b08 55%, #00ff41 100%)',
    },
    scene: {
      eyebrow: 'Terminal Reality Layer',
      headline: 'Decode the network stream before it becomes noise',
      description: 'A raw-signal workspace optimized for flow logs, threat classification, and precise console-style investigation.',
      mood: 'Phosphor terminal chamber',
      quote: 'Every anomaly leaves a trace.',
      signature: 'Greenline Console',
      strip: ['Trace Mode', 'Flow Decode', 'Terminal Watch'],
    },
    gpuCost: 'low',
    effects: {
      particles: true,
      scanlines: true,
      sakura: false,
      grid: false,
      glowIntensity: 0.4,
      terminalTyping: true,
    },
  },
  'mecha-hud': {
    id: 'mecha-hud',
    label: 'Mecha HUD',
    description: 'Red/gold tactical heads-up display for high-tempo response.',
    category: 'immersive',
    icon: 'ri-crosshair-2-line',
    font: "'Rajdhani', sans-serif",
    displayFont: "'Rajdhani', sans-serif",
    preview: {
      primary: '#ff4500',
      secondary: '#ffd700',
      surface: '#120303',
      gradient: 'linear-gradient(135deg, #050101 0%, #531400 55%, #ffd700 100%)',
    },
    scene: {
      eyebrow: 'Tactical Response HUD',
      headline: 'Lock threat vectors and keep the response loop tight',
      description: 'Segmented tactical panels, radar-style emphasis, and fast severity recognition for incident response.',
      mood: 'Armored command interface',
      quote: 'Target the signal, not the noise.',
      signature: 'Mecha HUD',
      strip: ['Target Lock', 'Response Arc', 'Armor Telemetry'],
    },
    gpuCost: 'medium',
    effects: {
      particles: true,
      scanlines: false,
      sakura: false,
      grid: true,
      glowIntensity: 0.5,
      terminalTyping: false,
    },
  },
  'anime-neon': {
    id: 'anime-neon',
    label: 'Anime Neon',
    description: 'Original neon-anime command scene with sakura motion and energy cards.',
    category: 'flagship',
    icon: 'ri-sparkling-2-line',
    font: "'Sora', 'Inter', sans-serif",
    displayFont: "'Space Grotesk', 'Sora', sans-serif",
    preview: {
      primary: '#b450ff',
      secondary: '#ff6bcb',
      surface: '#11081a',
      gradient: 'linear-gradient(135deg, #11081a 0%, #5d21a8 46%, #ff6bcb 72%, #4deeea 100%)',
    },
    scene: {
      eyebrow: 'Neon Sentinel Stage',
      headline: 'Defend the workspace with energy, clarity, and motion',
      description: 'A cinematic anime-inspired operations stage with original silhouettes, neon energy cards, and readable live security posture.',
      mood: 'Sakura-lit sentinel deck',
      quote: 'Focus the signal. Guard the horizon.',
      signature: 'Neon Sentinel',
      strip: ['Sentinel Aura', 'Sakura Drift', 'Energy Telemetry'],
    },
    gpuCost: 'medium',
    effects: {
      particles: true,
      scanlines: false,
      sakura: true,
      grid: false,
      glowIntensity: 0.6,
      terminalTyping: false,
    },
  },
  'space-station': {
    id: 'space-station',
    label: 'Space Station',
    description: 'Orbital operations console with deep-space calm and orange mission accents.',
    category: 'immersive',
    icon: 'ri-planet-line',
    font: "'Inter', sans-serif",
    displayFont: "'Space Grotesk', 'Inter', sans-serif",
    preview: {
      primary: '#ff8c00',
      secondary: '#4169e1',
      surface: '#020202',
      gradient: 'linear-gradient(135deg, #000000 0%, #081836 58%, #ff8c00 100%)',
    },
    scene: {
      eyebrow: 'Orbital Watch Floor',
      headline: 'Monitor the network from a quiet orbital command room',
      description: 'A mission-control view for stable monitoring, capacity planning, and calm long-running visibility.',
      mood: 'Orbital telemetry bay',
      quote: 'Distance creates perspective.',
      signature: 'Orbital Watch',
      strip: ['Orbit View', 'Telemetry Bay', 'Deep Signal'],
    },
    gpuCost: 'low',
    effects: {
      particles: true,
      scanlines: false,
      sakura: false,
      grid: false,
      glowIntensity: 0.1,
      terminalTyping: false,
    },
  },
  'tactical-military': {
    id: 'tactical-military',
    label: 'Tactical Military',
    description: 'Radar-green command interface for disciplined incident operations.',
    category: 'immersive',
    icon: 'ri-radar-line',
    font: "'Rajdhani', 'Inter', sans-serif",
    displayFont: "'Oswald', 'Rajdhani', sans-serif",
    preview: {
      primary: '#aadd00',
      secondary: '#d4af37',
      surface: '#141914',
      gradient: 'linear-gradient(135deg, #050605 0%, #1e281e 58%, #aadd00 100%)',
    },
    scene: {
      eyebrow: 'Field Operations Map',
      headline: 'Hold the perimeter with disciplined signal control',
      description: 'Radar-style situational awareness for assets, alerts, and defensive response lanes.',
      mood: 'Command tent radar wall',
      quote: 'Secure the perimeter. Verify the signal.',
      signature: 'Field Ops',
      strip: ['Radar Sweep', 'Perimeter', 'Asset Control'],
    },
    gpuCost: 'medium',
    effects: {
      particles: true,
      scanlines: true,
      sakura: false,
      grid: true,
      glowIntensity: 0.2,
      terminalTyping: false,
    },
  },
  'retro-hacker': {
    id: 'retro-hacker',
    label: 'Retro Hacker',
    description: 'Amber CRT command space for old-school operator focus.',
    category: 'immersive',
    icon: 'ri-tv-2-line',
    font: "'VT323', 'JetBrains Mono', monospace",
    displayFont: "'VT323', 'JetBrains Mono', monospace",
    preview: {
      primary: '#ffb000',
      secondary: '#ff8c00',
      surface: '#0a0500',
      gradient: 'linear-gradient(135deg, #000000 0%, #211300 62%, #ffb000 100%)',
    },
    scene: {
      eyebrow: 'Amber Console Room',
      headline: 'Investigate with a focused phosphor command surface',
      description: 'A low-distraction retro environment for logs, flows, and methodical forensic review.',
      mood: 'Amber CRT bunker',
      quote: 'Old screens. Sharp instincts.',
      signature: 'Amber Bunker',
      strip: ['CRT Mode', 'Forensic Trace', 'Low Noise'],
    },
    gpuCost: 'low',
    effects: {
      particles: true,
      scanlines: true,
      sakura: false,
      grid: false,
      glowIntensity: 0.3,
      terminalTyping: true,
    },
  },
  'ai-core': {
    id: 'ai-core',
    label: 'AI Core Interface',
    description: 'Clean neural interface for premium enterprise operations.',
    category: 'immersive',
    icon: 'ri-brain-line',
    font: "'Inter', sans-serif",
    displayFont: "'Orbitron', 'Inter', sans-serif",
    preview: {
      primary: '#0066ff',
      secondary: '#00ccff',
      surface: '#f0f4f8',
      gradient: 'linear-gradient(135deg, #f0f4f8 0%, #dbeafe 55%, #0066ff 100%)',
    },
    scene: {
      eyebrow: 'Neural Operations Core',
      headline: 'Let clean intelligence guide every response path',
      description: 'A sterile, high-clarity workspace for executive-grade monitoring and AI-assisted posture review.',
      mood: 'Neural glass chamber',
      quote: 'Intelligence should reduce friction.',
      signature: 'AI Core',
      strip: ['Neural Grid', 'Clean Signal', 'Decision Layer'],
    },
    gpuCost: 'medium',
    effects: {
      particles: true,
      scanlines: false,
      sakura: false,
      grid: true,
      glowIntensity: 0.4,
      terminalTyping: false,
    },
  },
};
