# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: alerts.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'alerts.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x61lerts.proto\x12\x0enetvisor.alert\x1a\x0c\x63ommon.proto\"\x9c\x02\n\rThreatFinding\x12\x0e\n\x06\x65ngine\x18\x01 \x01(\t\x12\x14\n\x0c\x66inding_type\x18\x02 \x01(\t\x12\x10\n\x08severity\x18\x03 \x01(\t\x12\x12\n\nconfidence\x18\x04 \x01(\x02\x12\x10\n\x08\x65vidence\x18\x05 \x03(\t\x12-\n\ttimestamp\x18\x06 \x01(\x0b\x32\x1a.netvisor.common.Timestamp\x12\x11\n\ttarget_ip\x18\x07 \x01(\t\x12;\n\x07\x64\x65tails\x18\x08 \x03(\x0b\x32*.netvisor.alert.ThreatFinding.DetailsEntry\x1a.\n\x0c\x44\x65tailsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xaa\x02\n\x0eIncidentReport\x12\x13\n\x0bincident_id\x18\x01 \x01(\t\x12\x17\n\x0forganization_id\x18\x02 \x01(\t\x12\x12\n\nprimary_ip\x18\x03 \x01(\t\x12\x10\n\x08severity\x18\x04 \x01(\t\x12\x1d\n\x15\x63umulative_risk_score\x18\x05 \x01(\x02\x12/\n\x08\x66indings\x18\x06 \x03(\x0b\x32\x1d.netvisor.alert.ThreatFinding\x12.\n\nfirst_seen\x18\x07 \x01(\x0b\x32\x1a.netvisor.common.Timestamp\x12-\n\tlast_seen\x18\x08 \x01(\x0b\x32\x1a.netvisor.common.Timestamp\x12\x15\n\rmitre_tactics\x18\t \x03(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'alerts_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_THREATFINDING_DETAILSENTRY']._loaded_options = None
  _globals['_THREATFINDING_DETAILSENTRY']._serialized_options = b'8\001'
  _globals['_THREATFINDING']._serialized_start=47
  _globals['_THREATFINDING']._serialized_end=331
  _globals['_THREATFINDING_DETAILSENTRY']._serialized_start=285
  _globals['_THREATFINDING_DETAILSENTRY']._serialized_end=331
  _globals['_INCIDENTREPORT']._serialized_start=334
  _globals['_INCIDENTREPORT']._serialized_end=632
# @@protoc_insertion_point(module_scope)
