# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x0fnetvisor.common\"+\n\tTimestamp\x12\x0f\n\x07seconds\x18\x01 \x01(\x03\x12\r\n\x05nanos\x18\x02 \x01(\x05\"\x86\x01\n\x0e\x43lientIdentity\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x17\n\x0forganization_id\x18\x02 \x01(\t\x12\x10\n\x08hostname\x18\x03 \x01(\t\x12\x12\n\nip_address\x18\x04 \x01(\t\x12\x11\n\tos_family\x18\x05 \x01(\t\x12\x0f\n\x07version\x18\x06 \x01(\t\"f\n\x11\x44iagnosticMetrics\x12\x11\n\tcpu_usage\x18\x01 \x01(\x02\x12\x11\n\tram_usage\x18\x02 \x01(\x02\x12\x16\n\x0euptime_seconds\x18\x03 \x01(\x03\x12\x13\n\x0bqueue_depth\x18\x04 \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TIMESTAMP']._serialized_start=33
  _globals['_TIMESTAMP']._serialized_end=76
  _globals['_CLIENTIDENTITY']._serialized_start=79
  _globals['_CLIENTIDENTITY']._serialized_end=213
  _globals['_DIAGNOSTICMETRICS']._serialized_start=215
  _globals['_DIAGNOSTICMETRICS']._serialized_end=317
# @@protoc_insertion_point(module_scope)
