# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: flow.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'flow.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nflow.proto\x12\rnetvisor.flow\x1a\x0c\x63ommon.proto\"\xdb\x02\n\x0f\x46lowObservation\x12\x0e\n\x06src_ip\x18\x01 \x01(\t\x12\x0e\n\x06\x64st_ip\x18\x02 \x01(\t\x12\x10\n\x08src_port\x18\x03 \x01(\x05\x12\x10\n\x08\x64st_port\x18\x04 \x01(\x05\x12\x10\n\x08protocol\x18\x05 \x01(\t\x12\x14\n\x0cpacket_count\x18\x06 \x01(\x03\x12\x12\n\nbyte_count\x18\x07 \x01(\x03\x12\x10\n\x08\x64uration\x18\x08 \x01(\x01\x12\x0e\n\x06\x64omain\x18\t \x01(\t\x12\x0b\n\x03sni\x18\n \x01(\t\x12\x0f\n\x07src_mac\x18\x0b \x01(\t\x12\x0f\n\x07\x64st_mac\x18\x0c \x01(\t\x12.\n\nstart_time\x18\r \x01(\x0b\x32\x1a.netvisor.common.Timestamp\x12-\n\tlast_seen\x18\x0e \x01(\x0b\x32\x1a.netvisor.common.Timestamp\x12\x18\n\x10\x61nalysis_signals\x18\x0f \x03(\t\"\xb2\x01\n\tFlowBatch\x12/\n\x06sender\x18\x01 \x01(\x0b\x32\x1f.netvisor.common.ClientIdentity\x12-\n\x05\x66lows\x18\x02 \x03(\x0b\x32\x1e.netvisor.flow.FlowObservation\x12\x33\n\x0f\x62\x61tch_timestamp\x18\x03 \x01(\x0b\x32\x1a.netvisor.common.Timestamp\x12\x10\n\x08\x62\x61tch_id\x18\x04 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'flow_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FLOWOBSERVATION']._serialized_start=44
  _globals['_FLOWOBSERVATION']._serialized_end=391
  _globals['_FLOWBATCH']._serialized_start=394
  _globals['_FLOWBATCH']._serialized_end=572
# @@protoc_insertion_point(module_scope)
