# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: handshake.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'handshake.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fhandshake.proto\x12\x12netvisor.handshake\x1a\x0c\x63ommon.proto\"\xaa\x01\n\x10HandshakeRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x18\n\x10protocol_version\x18\x02 \x01(\t\x12\x1e\n\x16supported_capabilities\x18\x03 \x03(\t\x12-\n\ttimestamp\x18\x04 \x01(\x0b\x32\x1a.netvisor.common.Timestamp\x12\x1b\n\x13machine_fingerprint\x18\x05 \x01(\t\"\xc7\x02\n\x11HandshakeResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x13\n\x0bsession_jwt\x18\x02 \x01(\t\x12#\n\x1bnegotiated_protocol_version\x18\x03 \x01(\t\x12\x1c\n\x14\x65nabled_capabilities\x18\x04 \x03(\t\x12N\n\rfeature_flags\x18\x05 \x03(\x0b\x32\x37.netvisor.handshake.HandshakeResponse.FeatureFlagsEntry\x12\x15\n\rerror_message\x18\x06 \x01(\t\x12.\n\nexpires_at\x18\x07 \x01(\x0b\x32\x1a.netvisor.common.Timestamp\x1a\x33\n\x11\x46\x65\x61tureFlagsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'handshake_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HANDSHAKERESPONSE_FEATUREFLAGSENTRY']._loaded_options = None
  _globals['_HANDSHAKERESPONSE_FEATUREFLAGSENTRY']._serialized_options = b'8\001'
  _globals['_HANDSHAKEREQUEST']._serialized_start=54
  _globals['_HANDSHAKEREQUEST']._serialized_end=224
  _globals['_HANDSHAKERESPONSE']._serialized_start=227
  _globals['_HANDSHAKERESPONSE']._serialized_end=554
  _globals['_HANDSHAKERESPONSE_FEATUREFLAGSENTRY']._serialized_start=503
  _globals['_HANDSHAKERESPONSE_FEATUREFLAGSENTRY']._serialized_end=554
# @@protoc_insertion_point(module_scope)
