# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: health.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'health.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0chealth.proto\x12\x0fnetvisor.health\x1a\x0c\x63ommon.proto\"\xc8\x01\n\nHealthPing\x12/\n\x06sender\x18\x01 \x01(\x0b\x32\x1f.netvisor.common.ClientIdentity\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.netvisor.common.Timestamp\x12\x33\n\x07metrics\x18\x03 \x01(\x0b\x32\".netvisor.common.DiagnosticMetrics\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x15\n\ractive_errors\x18\x05 \x03(\t\"p\n\x14HealthStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x17\n\x0frequest_metrics\x18\x02 \x01(\x08\x12/\n\x0bserver_time\x18\x03 \x01(\x0b\x32\x1a.netvisor.common.Timestampb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'health_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHPING']._serialized_start=48
  _globals['_HEALTHPING']._serialized_end=248
  _globals['_HEALTHSTATUSRESPONSE']._serialized_start=250
  _globals['_HEALTHSTATUSRESPONSE']._serialized_end=362
# @@protoc_insertion_point(module_scope)
