"""Shared packet capture and flow aggregation helpers (re-exported from packet_engine for backward compatibility)."""

from packet_engine import (
    CaptureBackend,
    DomainHintCache,
    DpiObservation,
    FlowKey,
    FlowManager,
    FlowObservation,
    FlowState,
    FlowSummary,
    LinuxRawSocketCaptureBackend,
    PacketAnalysis,
    PacketObservation,
    PreflightResult,
    ScapyCaptureBackend,
    analyze_packet,
    build_capture_backend,
    extract_domain_hint,
    extract_flow_hints,
    preflight_exit_code,
    print_preflight_report,
    run_preflight,
    serialize_preflight_results,
)

__all__ = [
    "CaptureBackend",
    "DomainHintCache",
    "DpiObservation",
    "FlowKey",
    "FlowManager",
    "FlowObservation",
    "FlowState",
    "FlowSummary",
    "LinuxRawSocketCaptureBackend",
    "PacketAnalysis",
    "PacketObservation",
    "PreflightResult",
    "ScapyCaptureBackend",
    "preflight_exit_code",
    "build_capture_backend",
    "analyze_packet",
    "extract_domain_hint",
    "extract_flow_hints",
    "print_preflight_report",
    "run_preflight",
    "serialize_preflight_results",
]
